from machine import Pin
from machine import PWM
import time
import neopixel

# Initialize the button
initiate_button = Pin(20, Pin.IN, Pin.PULL_UP)  # Assuming pin 8 is connected to the initiate button

# RGB
num_pixels = 2  # Replace with the actual number of Neopixel LEDs
neopixel_pin = Pin(18, Pin.OUT)  # Replace with the correct pin
np = neopixel.NeoPixel(neopixel_pin, num_pixels)

def gpio_set(pin,value):
  if value >= 1:
    Pin(pin, Pin.OUT).on()
  else:
    Pin(pin, Pin.OUT).off()

# Describe this function...
def move_stop():
  gpio_set((9), False)
  gpio_set((11), False)
  time.sleep(1)
  np.fill((255, 100, 100))  # Red
  np.write()

# Describe this function...
def move_forward():
  pwm9 = PWM(Pin(9))
  pwm9.freq(1000)
  pwm9.duty_u16(5)
  gpio_set((9), True)
  pwm11 = PWM(Pin(11))
  pwm11.freq(1000)
  pwm11.duty_u16(5)
  gpio_set((11), True)
  np.fill((100, 255, 255))  # Blue
  np.write()

# Describe this function...
def turn_right_junction():
  for count in range(2):
    time.sleep(0.5)
    pwm22 = PWM(Pin(22))
    pwm22 = PWM(Pin(22))
    pwm22.freq(400)
    pwm22.duty_u16(1000)
    time.sleep(1)
    pwm22.deinit()
  pwm11 = PWM(Pin(11))
  pwm11.freq(1000)
  pwm11.duty_u16(5)
  gpio_set((9), False)
  gpio_set((11), True)
  time.sleep(0.6)

# Describe this function...
def turn_right_pos():
  pwm11 = PWM(Pin(11))
  pwm11.freq(1000)
  pwm11.duty_u16(5)
  gpio_set((9), False)
  gpio_set((11), True)
  np.fill((128, 0, 128))  # gray
  np.write()

# Describe this function...
def turnleftt_IR_sensor_light2():
  pwm9 = PWM(Pin(9))
  pwm9.freq(1000)
  pwm9.duty_u16(5)
  gpio_set((9), True)
  gpio_set((11), False)
  np.fill((100, 255, 100))  # Green
  np.write()

pIn0=Pin(0, Pin.IN, Pin.PULL_UP)

pIn7=Pin(7, Pin.IN, Pin.PULL_UP)

#Code automatically generated by BIPES (http://www.bipes.net.br)
#Author: 'User'
#IOT ID: 0
#Description: 'Masa depan ubah'

while True:
    # Wait for the initiate button to be pressed
    while initiate_button.value() == 1:
        pass

    # Record the start time
    start_time = time.ticks_ms()
    timeout = 17400 #17.9 seconds

    # Main loop with a 18-second timeout
    while time.ticks_ms() - start_time < timeout:
        if (pIn0.value()) == 0 and (pIn7.value()) == 0:
            move_forward()
        elif (pIn0.value()) == 1 and (pIn7.value()) == 1:
            move_stop()
            turn_right_junction()
        elif (pIn0.value()) == 0 and (pIn7.value()) == 1:
            turn_right_pos()
        elif (pIn0.value()) == 1 and (pIn7.value()) == 0:
            turnleftt_IR_sensor_light2()

    # Stop the robot after the timer ends
    move_stop()
